### PR TITLE
Removed old members from the website

### PR DESCRIPTION
**Pull request by V3dant**
#1 Removed Siddhant Singh, Anushka Shukla & Dania Alam from the underdog crew.

### CODE REVIEW

**Comment by V3dant** [comment]
Removed these guys from the crew page.
Siddhant Singh
Anushka Shukla
Dania Alam

**Comment by V3dant** [comment]
And removed Srishti Shukla from the carousel.

**Comment by akshat0047** [comment]
@V3dant Its great that you have accomplished the task but this is the wrong workflow to work on an OpenSource project. As mentioned in my text, you need to tell if you're working on an issue by commenting on it and the maintainer provides you the approval for the same.

Also 1 PR = 1 Issue

I know the issues were minor but they were made so to help budding contributors to OpenSource
Please follow these steps:-

- Comment on the issue you want to work
- Only do the changes asked in that particular issue
- Push them to your forke copy and they will get considere in this PR.

(Your doubts are welcome)

**Comment by V3dant** [comment]
Okay, I'll keep that in mind from next time. But I've made the changes you asked for and created a pull request there's no going back for me.

**Comment by akshat0047** [comment]
There is for sure just do a hard reset to one previous commit and force push to your origin.

**Pull request closed without merging**
